### ISSUE TITLE
Correccion en Gulpfile

### ISSUE THREAD

**Issue by gerardoarambulo** [escueladigital/EDboilerplate#1]
Revisa estas lineas Edteam...

 watch('./src/scss/**/*.scss', () => gulp.start('styles'));
 watch('./src/js/**/*.js', () => gulp.start('scripts',server.reload) );
 watch('./src/pug/**/*.js', () => gulp.start('pug', server.reload) );

Saludos!

**Comment by escueladigital** [comment]
No entiendo, ¿cuál es el problema con esas líneas?

**Comment by gerardoarambulo** [comment]
La tercera linea busca un JS en lugar del pug, solo eso :)

**Comment by escueladigital** [comment]
uy verdad 😅
